name: Hello World 

on:
  push:
    branch:
      -main
  pull_request:
    branch: [main]
    types: [open, synchronize]

jobs:
  hello_world_job:
    run-on: ubuntu-20.04
    steps:
      - name: Say Hello
        run: echo "Hello World"